# Generated by Django 4.0.6 on 2022-11-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorText', models.CharField(blank=True, max_length=50, null=True)),
                ('backGround', models.ImageField(blank=True, max_length=3000000, null=True, upload_to='back/')),
                ('logo', models.ImageField(blank=True, max_length=3000000, null=True, upload_to='back/')),
            ],
        ),
        migrations.AlterField(
            model_name='detailtoship',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsshipp',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.detailtoship'),
        ),
        migrations.AlterField(
            model_name='goodsshipp',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
