# Generated by Django 4.0.6 on 2022-11-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_decor_alter_detailtoship_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsshipp',
            name='BarIMage',
            field=models.FileField(blank=True, null=True, upload_to='barcode/'),
        ),
    ]
