# Generated by Django 4.0.6 on 2022-11-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_goodsshipp_barimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsshipp',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
