# Generated by Django 4.0.6 on 2022-11-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_goodsshipp_serialnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsshipp',
            name='BarIMage',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
